import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import "react-toastify/ReactToastify.css"
import { AuthProvider } from "<prefix>/context/userContext";
import Lsidebar from "<prefix>/components/lsidebar";
import Wrapper from "<prefix>/components/wrapper";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <div className="relative flex w-full min-h-screen">
            <Wrapper>
              <div className="hidden lg:block w-64 z-20">
                <Lsidebar />
              </div>
              <main className="relative z-30 flex-grow p-4">{children}</main>
            </Wrapper>
          </div>
          <ToastContainer position="top-right" autoClose={3000} hideProgressBar />
        </AuthProvider>
      </body>
    </html>
  )
}
